# Generated by Django 6.0.1 on 2026-02-23 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0002_alter_perfilusuario_user_reporteusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoSectorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('NAVAL', 'Naval'), ('ENERGIA', 'Energía'), ('AEREO', 'Aéreo'), ('AGRO', 'Agropecuario')], max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_principal', models.FloatField(help_text='Valor principal del sector')),
                ('valor_secundario', models.FloatField(blank=True, help_text='Valor secundario opcional', null=True)),
                ('ubicacion', models.CharField(help_text='Ubicación geográfica', max_length=255)),
                ('analisis_ia', models.TextField(help_text='Análisis generado por IA')),
                ('metadatos', models.JSONField(default=dict, help_text='Datos específicos del sector')),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato Sectorial',
                'verbose_name_plural': 'Datos Sectoriales',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
