# Generated by Django 6.0.1 on 2026-03-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0003_datosectorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('NAVAL', 'Naval'), ('ENERGIA', 'Energía'), ('AEREO', 'Aéreo'), ('AGRO', 'Agropecuario')], help_text='Sector donde se generó el feedback', max_length=10)),
                ('tipo_feedback', models.CharField(choices=[('LIKE', 'Me gusta'), ('DISLIKE', 'No me gusta'), ('COMENTARIO', 'Comentario')], max_length=15)),
                ('mensaje_ia', models.TextField(help_text='Mensaje de la IA que recibió feedback')),
                ('comentario', models.TextField(blank=True, help_text='Comentario del usuario (opcional)', null=True)),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión del chat', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False, help_text='Marcado como revisado por administrador')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas del administrador', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que dejó el feedback (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback IA',
                'verbose_name_plural': 'Feedbacks IA',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='mundo_feedb_fecha_c_bd3b6f_idx'), models.Index(fields=['sector', '-fecha_creacion'], name='mundo_feedb_sector_5ea1a5_idx'), models.Index(fields=['tipo_feedback', '-fecha_creacion'], name='mundo_feedb_tipo_fe_7dc82d_idx')],
            },
        ),
    ]
