# Generated by Django 6.0.1 on 2026-03-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0004_feedbackia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='plan_tipo',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual ($20/mes)'), ('anual', 'Anual ($200/año)')], default='mensual', max_length=10),
        ),
    ]
