# Generated by Django 6.0.1 on 2026-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0005_add_plan_tipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='renovacion_automatica',
            field=models.BooleanField(default=True, help_text='Recibir recordatorio por email 5 días antes del vencimiento', verbose_name='Renovación automática'),
        ),
    ]
