# Generated by Django 6.0.1 on 2026-03-13 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0006_add_renovacion_automatica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tokens_disponibles',
            field=models.IntegerField(default=0, help_text='Créditos de IA disponibles (Gemini Pro)', verbose_name='Tokens disponibles'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tokens_usados_total',
            field=models.IntegerField(default=0, verbose_name='Tokens usados (total histórico)'),
        ),
        migrations.CreateModel(
            name='HistorialTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USO', 'Uso IA'), ('RECARGA', 'Recarga pagada'), ('BONO', 'Bono / activación suscripción')], max_length=10)),
                ('cantidad', models.IntegerField(help_text='Positivo = recarga, Negativo = consumo')),
                ('descripcion', models.CharField(max_length=255)),
                ('tokens_restantes', models.IntegerField(help_text='Saldo tras esta operación')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Tokens',
                'verbose_name_plural': 'Historial de Tokens',
                'ordering': ['-fecha'],
            },
        ),
    ]
