# Generated by Django 6.0.1 on 2026-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0007_tokens_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_vencimiento_tokens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento plan tokens'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tokens_diarios_limite',
            field=models.IntegerField(default=0, help_text='0 = sin plan diario activo', verbose_name='Límite diario de tokens'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_recarga_diaria',
            field=models.DateField(blank=True, null=True, verbose_name='Última recarga diaria'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tokens_disponibles',
            field=models.IntegerField(default=0, help_text='Créditos de IA disponibles para hoy', verbose_name='Tokens disponibles hoy'),
        ),
    ]
