# Generated by Django 6.0.1 on 2026-03-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0009_alertas_proactivas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sector_elegido',
            field=models.CharField(blank=True, default='', help_text='Para plan Starter: sector al que tiene acceso. Vacío = puede elegir.', max_length=10, verbose_name='Sector elegido (Starter)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='alertas_sectores',
            field=models.CharField(blank=True, default='', help_text='Ej: agro,naval — vacío = sin alertas configuradas', max_length=50, verbose_name='Sectores de alerta'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='hora_alerta',
            field=models.IntegerField(default=7, help_text='Hora local Argentina (0-23)', verbose_name='Hora de envío (Argentina)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ubicacion_nombre',
            field=models.CharField(blank=True, default='', help_text='Ciudad o localidad, ej: Buenos Aires', max_length=100, verbose_name='Ubicación para alertas'),
        ),
    ]
