# Generated by Django 6.0.1 on 2026-03-23 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0010_add_sector_elegido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(default='Mi API Key', max_length=60)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key personal',
                'verbose_name_plural': 'API keys personales',
            },
        ),
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('agro', 'Agropecuario'), ('naval', 'Naval'), ('aereo', 'Aéreo'), ('energia', 'Energía')], max_length=10)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=10)),
                ('hora_envio', models.PositiveSmallIntegerField(default=8, help_text='Hora UTC (0–23) en la que se envía el reporte')),
                ('email_destino', models.EmailField(blank=True, help_text='Dejar vacío para usar el email de la cuenta', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_programados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte programado',
                'verbose_name_plural': 'Reportes programados',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sector', models.CharField(blank=True, help_text='Sector preferido para esta ubicación: agro/naval/aereo/energia', max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación guardada',
                'verbose_name_plural': 'Ubicaciones guardadas',
                'ordering': ['-es_principal', '-creada'],
            },
        ),
    ]
