"""
Django settings for nucleo project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Cargar variables de entorno ANTES de cualquier configuración
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'tuclima-mundial.onrender.com',
    '*'  # Solo para desarrollo
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mundo',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nucleo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nucleo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuración mejorada de base de datos con persistencia garantizada
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=0,           # Transaction pooler requiere conn_max_age=0
        conn_health_checks=False,
    )
}

ATOMIC_REQUESTS = False

# Transaction pooler NO soporta 'PREPARE' ni opciones de sesión
DATABASES['default']['OPTIONS'] = {
    'connect_timeout': 30,
    'sslmode': 'require',
}

# ============================================================
# CACHÉ DE DJANGO — persiste en la base de datos PostgreSQL
# Sobrevive reinicios del servidor (a diferencia de memoria RAM).
# TTL por defecto: 30 minutos (1800 s). Se crea la tabla con:
#   python manage.py createcachetable
# ============================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_clima',
        'TIMEOUT': 1800,  # 30 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



import os

# Configuraciones de archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'mundo/static')]

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuraciones de autenticación
LOGIN_URL = '/login/'

# Configuraciones de idioma
LANGUAGE_CODE = 'es'  # Cambiado a español como principal

# Activamos la traducción
USE_I18N = True
USE_L10N = True

# Definimos los idiomas disponibles
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
]

# Configuraciones de CSRF para producción y desarrollo
CSRF_TRUSTED_ORIGINS = [
    'https://tuclima-mundial.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000'
]

# ============================================================
# EMAIL (SMTP) — configura estas variables en tu .env
# Gmail: EMAIL_HOST_USER=tu@gmail.com  EMAIL_HOST_PASSWORD=app_password_16_chars
# ============================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST      = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT      = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS   = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', 'Weather Pro <climapro00@gmail.com>')

# ============================================================
# MERCADOPAGO — configura en .env
# MP_ACCESS_TOKEN=APP_USR-...    (producción)
# MP_PUBLIC_KEY=APP_USR-...      (front-end, no usada en backend)
# SITE_URL=https://tuclima-mundial.onrender.com  (para webhooks y back_urls)
# ============================================================
MP_ACCESS_TOKEN = os.getenv('MP_ACCESS_TOKEN', '')
SITE_URL        = os.getenv('SITE_URL', 'http://127.0.0.1:8000')  # ngrok en desarrollo

# ============================================================
# PAYPAL — configura en .env
# PAYPAL_MODE=sandbox (desarrollo) o live (producción)
# PAYPAL_CLIENT_ID=<tu_client_id>
# PAYPAL_CLIENT_SECRET=<tu_client_secret>
# ============================================================
PAYPAL_MODE          = os.getenv('PAYPAL_MODE', 'sandbox')
PAYPAL_CLIENT_ID     = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')

# ============================================================
# LEMON SQUEEZY
# LEMONSQUEEZY_STORE_SLUG: slug de la tienda (ej: "tuclima-mundial")
# LEMONSQUEEZY_STORE_ID:   ID numérico de la tienda (lo ves en LS → Settings → Store)
# LEMONSQUEEZY_API_KEY:    API key de LS (https://app.lemonsqueezy.com/settings/api)
# LEMONSQUEEZY_WEBHOOK_SECRET: whsec_... (LS → Settings → Webhooks)
# ============================================================
LEMONSQUEEZY_STORE_SLUG       = os.getenv('LEMONSQUEEZY_STORE_SLUG', '')
LEMONSQUEEZY_STORE_ID         = os.getenv('LEMONSQUEEZY_STORE_ID', '')
LEMONSQUEEZY_API_KEY          = os.getenv('LEMONSQUEEZY_API_KEY', '')
LEMONSQUEEZY_WEBHOOK_SECRET   = os.getenv('LEMONSQUEEZY_WEBHOOK_SECRET', '')

# ============================================================
# ALERTAS PROACTIVAS (n8n)
# N8N_ALERTAS_SECRET=tuclima-alertas-2026  (mismo valor en n8n y en esta variable)
# ============================================================
N8N_ALERTAS_SECRET = os.getenv('N8N_ALERTAS_SECRET', '')
